version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service:/var/www
    depends_on:
      - auth-db
    networks:
      - app-net

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "33061:3306"
    networks:
      - app-net

  auth-test-db:
    image: mysql:8.0
    container_name: auth-test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_test_db
    ports:
      - "33063:3306"
    networks:
      - app-net

  ip-service:
    build:
      context: ./ip-management-service
    container_name: ip-service
    ports:
      - "8002:8000"
    volumes:
      - ./ip-management-service:/var/www
    depends_on:
      - ip-db
    networks:
      - app-net

  ip-db:
    image: mysql:8.0
    container_name: ip-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ip_db
    ports:
      - "33062:3306"
    networks:
      - app-net

  ip-test-db:
    image: mysql:8.0
    container_name: ip-test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ip_test_db
    ports:
      - "33064:3306"
    networks:
      - app-net

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    volumes:
      - ./gateway-service:/var/www
    depends_on:
      - auth-service
      - ip-service
    networks:
      - app-net

  audit-service:
    build:
      context: ./audit-service
    container_name: audit-service
    ports:
      - "8003:8000"
    volumes:
      - ./audit-service:/var/www
    depends_on:
      - audit-db
    networks:
      - app-net

  audit-db:
    image: mysql:8.0
    container_name: audit-db
    ports:
      - "33065:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: audit_db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge